<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />
  <Import Project="..\..\configureawait.props" />
  
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>Abp.Mapperly</AssemblyName>
    <PackageId>Abp.Mapperly</PackageId>
    <PackageTags>asp.net;asp.net mvc;boilerplate;application framework;web framework;framework;domain driven design;mapperly;object mapper;source generator</PackageTags>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <RootNamespace>Abp</RootNamespace>
    <Description>Abp.Mapperly</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abp\Abp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Riok.Mapperly" Version="4.1.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Fody" Version="6.9.3" />
  </ItemGroup>

</Project>
